Test1

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,35 +10,61 @@ jobs:
   release:
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
       - name: Login to Docker Hub
-        uses: docker/login-action@v2
+        uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
 
-      - name: Install Go
-        uses: actions/setup-go@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
+
+      - name: Build and push
+        id: build
+        uses: docker/build-push-action@v2
+        continue-on-error: true
         with:
-          go-version: 1.18
-
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Fetch required Go modules
-        run: go mod download
-
-      - name: Build
-        run: go build -v ./...
-
-      - name: Test
-        run: go test -v ./...
-
-      - name: Build and push Docker image
-        id: docker_build
-        uses: docker/build-push-action@v3
-        with:
+          context: .
+          file: ./Dockerfile
           push: true
-          tags: ${{ secrets.DOCKER_USERNAME }}/golangapi:latest
+          tags: ${{ secrets.DOCKER_USERNAME }}/golangapi:lastest
 
-      - name: Image digest
-        run: echo ${{ steps.docker_build.outputs.digest }}
+      # - name: Call Portainer Webhook to Update Service
+      #   id: callportainerwebhook
+      #   if: steps.build.outcome == 'success'
+      #   continue-on-error: true
+      #   run: |
+
+      #     CODE=`curl --write-out '%{http_code}' \
+      #         --silent \
+      #         --output /dev/null \
+      #         --request POST \
+      #         --url 'https://portainer.kokkoksole.com/api/webhooks/f51099da-0414-4cf4-b616-666fe0f42dbe'`
+
+      #     if [ $CODE != "204" ]
+      #     then
+      #         echo $CODE
+      #         echo "FAILURE"
+      #         exit 1
+      #     else
+      #         echo $CODE
+      #         echo "SUCCESS"
+      #         exit 0
+      #     fi
+
+      # - name: Sent LINE Noti - Success
+      #   if: steps.build.outcome == 'success' && steps.callportainerwebhook.outcome == 'success'
+      #   uses: snow-actions/line-notify@v1.0.0
+      #   with:
+      #     access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
+      #     message: "👏 Backend | build and deploy มีการอัปเดตเรื่อง ${{ github.event.commits[0].message }} ของ ${{ github.event.commits[0].author.name }} เสร็จแล้ว รอโปรแกรม Compile 1 นาที แล้วทดสอบได้เลย 😎"
+
+      # - name: Sent LINE Noti - Failure
+      #   if: steps.build.outcome != 'success' || steps.callportainerwebhook.outcome != 'success'
+      #   uses: snow-actions/line-notify@v1.0.0
+      #   with:
+      #     access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
+      #     message: "❌❌❌  Backend - Build Error เรื่อง ${{ github.event.commits[0].message }} ของ ${{ github.event.commits[0].author.name }} โปรดตรวจสอบ"
